Models
tenatarika/showroom pull request #1
Opened 2021-10-13 08:41 UTC by tenatarika

2021-10-18 12:50 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/admin.py
> +# Register your models here.
Зарегистрируй модельки в админке, используя классы, потренируйся кастомить админ страничку

2021-10-18 12:51 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +class Car_showroom(models.Model):
Название модели в camel case -> CarShowroom

2021-10-18 12:51 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +
две строки пустые перед классом

2021-10-18 12:51 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +
Слишком много пустых строк, нужно 2

2021-10-18 12:52 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +    car = models.ManyToManyField(Car, through='Car_showroom_Car')
В множественном числе

2021-10-18 12:52 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +    description = models.TextField(blank=True, max_length=255)
В TextField max_length указывать не нужно

2021-10-18 12:54 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    return [0, 0]
Почему именно такое дефолтное значение?

2021-10-18 12:55 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    return [0, 0]
Используешь в нескольких модулях с модельками в разных аппах, значит выноси общую логику, такую как здесь в core

2021-10-18 12:55 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    phone = models.CharField(max_length=14)
Добавь RegexValidator на только белорусский валидный номер

2021-10-18 12:55 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    sample = models.JSONField(blank=True, default=jsonfield_default_value)
Для чего это поле?

2021-10-18 12:55 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +
Одна пустая строка

2021-10-18 12:56 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +
одна пустая строка

2021-10-18 12:56 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +    vin = models.CharField(max_length=17, unique=True)
Добавь больше полей для характеристики автомобиля

2021-10-18 12:57 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +
Две пустые строки и перед и после класса

2021-10-18 12:57 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +    car = models.ManyToManyField(Car, through='Supplier_Car')
cars - для связи m2m поля должны быть во множественном числе

2021-10-18 12:57 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +class Supplier_Car(models.Model):
camel case -> SupplierCar

2021-11-02 15:12 UTC, isoldatenko requested changes

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +    balance = models.DecimalField(max_digits=14, decimal_places=2)
валидация на то, что баланс не меньше 0

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +    country = CountryField(default=None, blank=True)
можно выделить отдельную модель Адрес (страна / город / улица / номер дома)

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +                          validators=[MinValueValidator(0),
поставь минимум 1, потому что скипа = 0, по факту не скидка

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +                            related_name='cars_of_showroom', related_query_name='car_of_showroom',
related_name во множественном

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +                            related_name='cars_of_showroom', related_query_name='car_of_showroom',
по факту можно использовать просто `cars`

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +
одна пустая строка между импортами

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +        FEMALE = "Female"
вынеси в core и используй enum (встроенный модуль)

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    country = CountryField(default=None, blank=True)
тут тоже модель адреса можно выделить

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +        validators=(MinValueValidator(0),
тоже минимум 1

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +        GRAY = "Gray"
enum

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +    year = models.PositiveIntegerField(blank=True, default='1900')
поставь валидация на максимальный год - 2021

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +    price = models.DecimalField(max_digits=10, decimal_places=2)
валидация, что не может быть меньше нуля

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +        default=1)
валидация добавь, минимум - 1, максимум - 100

2021-11-02 15:12 UTC, isoldatenko commented on car_showroom_app/src/tools/fields.py
> +    is_available = models.BooleanField(default=True)
лишнее поле, по факту аналог - is_active

2021-11-06 08:35 UTC, isoldatenko requested changes

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/core/car_showroom/colors.py
> +    _GRAY = "Gray"
зачем `_` в начале?

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/core/customer/gender.py
> +    _FEMALE = "Female"
Зачем `_`  в начале?

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/core/car_showroom/colors.py
> +    _GRAY = "Gray"
Лучше разбивай enum по приложениям, а не по их назначению, т.е. если относится к автосалонам, то в модуль car_showroom добавляешь, получается что модуль Colors лишний, который ты тут создал

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/customer/admin.py
> +            return None
почему не использовать тут result.get("discount__avg") вместо блока try - except

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/supplier/admin.py
> +            return None
зачем тут блок try - except?

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/tools/fields.py
> +        return super(DecimalRangeField, self).formfield(**defaults)
кастомные филы давай хранить отдельно от моделек

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +    date = models.DateTimeField(auto_now=True)
такое же поле по факту есть в CreatedAt модели

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/car_showroom/models.py
> +                                     null=True, blank=True)
тут должен быть on_delete=models.CASCADE

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    houseNum = models.PositiveIntegerField(default=None, blank=True, null=True)
snake case -> house_num

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +    gender = models.CharField(choices=Gender.choices(), default="MALE", max_length=50)
max_length должен равняться максимальному значению из enum'a соответствующего, там хранится явно не 50 символов, а меньше

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/customer/models.py
> +                                     null=True, blank=True)
клиент покупает у автосалона, в этом случае ссылка на поставщика лишняя

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +    )
Supplier не должен хранить баланс, обговорили, что у него бесконечное количество машин

2021-11-06 08:35 UTC, isoldatenko commented on car_showroom_app/src/supplier/models.py
> +                                 null=True)
должно быть on_delete=models.CASCADE

2021-11-06 08:48 UTC, tenatarika commented on car_showroom_app/src/supplier/models.py
> +    )
Но когда шоу рум  покупает машины у саплаира, то  деньги шоу рума переходят на счет саплаиру

2021-11-10 14:13 UTC, isoldatenko requested changes

2021-11-10 14:13 UTC, isoldatenko commented on car_showroom_app/src/core/enums/customer.py
> +    _FEMALE = "Female"
Вот тут еще нижние подчеркивания убрать нужно

2021-11-10 14:17 UTC, isoldatenko approved these changes

2021-11-10 14:19 UTC, merged